cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :edit, :create, :update]

  resources :cat_rental_requests, only: [:new, :create]

  patch 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve', as: 'cat_rental_request_approve'

  patch 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny', as: 'cat_rental_request_deny'
end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ["black", "white", "brown", "orange"].freeze
  SEX = ["M", "F"].freeze

  def self.COLORS
    COLORS
  end

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: SEX }

  has_many :rental_requests,
  class_name: :CatRentalRequest,
  primary_key: :id,
  foreign_key: :cat_id,
  dependent: :destroy


  def age
    time_ago_in_words(birth_date)
  end

end

cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUS = ["PENDING", "APPROVED", "DENIED"]

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUS }
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    class_name: :Cat,
    primary_key: :id,
    foreign_key: :cat_id


  def overlapping_requests
    CatRentalRequest.where("start_date BETWEEN ? AND ? OR end_date BETWEEN ? AND ?",
                            start_date, end_date, start_date, end_date)
                    .where(cat_id: cat_id)
                    .where.not(id: id)

  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def approve!
    CatRentalRequest.transaction do
      self.overlapping_pending_requests.each(&:deny!)
      self.update(status: "APPROVED")
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = ?", 'PENDING')
  end

  def deny!
    self.update!(status: "DENIED")
  end

  def pending?
    status == 'PENDING'
  end

  private

  def does_not_overlap_approved_request

    return if self.status == 'DENIED'
    if overlapping_approved_requests.any?
      errors[:status] << 'already rented out'
    end
  end
end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController


  def new
    @cats = Cat.all
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      render json: @request.errors.full_messages, status: :unprocessable_entity
    end
  end

  def approve
    @request = CatRentalRequest.find_by(id: params[:id])
    if @request.approve!
      redirect_to cats_url
    else
      render json: @request.errors.full_messages
    end
  end

  def deny
    @request = CatRentalRequest.find_by(id: params[:id])
    @request.deny!
    redirect_to cats_url
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id,:start_date,:end_date)
  end
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end

end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

cats/app/helpers/cats_helper.rb
module CatsHelper
end

cats/app/views/cat_rental_requests/new.html.erb
<h2>Submit your rental request here</h2>
<form action = '<%=cat_rental_requests_url%>' method="post">

  <select name="cat_rental_request[cat_id]">
    <option disabled selected>--Select the cat--</option>
    <% @cats.each do |cat| %>
    <option value= <%= cat.id %> > <%= cat.name %> </option>
    <% end %>
  </select>

  <label for="start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="start_date">
  <label for="end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]"id = "end_date">

  <input type="submit" value="Submit request">
</form>

cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input type="text" name="cat[name]" id = "name" value= <%= cat.name ? cat.name : "" %> >
  <br>

  <label>Sex</label>
  <input type="radio" name="cat[sex]" value="M" id = "M" <%= cat.sex == "M" ? "checked" : "" %> >
  <label for="M">Male</label>
  <input type="radio" name="cat[sex]" value="F" id = "F" <%= cat.sex == "F" ? "checked" : "" %> >
  <label for="F">Female</label>

  <br>
  <label for="color">Color</label>
    <select name="cat[color]">
      <option disabled <%= cat.color ? "" : "selected" %> >-- select a color --</option>
      <% Cat.COLORS.each do |color| %>
        <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %> ><%= color %></option>
      <% end %>
  </select>

  <br>
  <label for="birth_date">Date of Birth</label>
  <input type="date" name="cat[birth_date]" value= <%= cat.birth_date ? cat.birth_date : "" %> >

  <br>
  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description ? cat.description : "" %>
  </textarea>

  <br>
    <input type="submit" value= <%= cat.persisted? ? "Update cat!" : "Add cat!" %> >
</form>

cats/app/views/cats/edit.html.erb
<h2>Edit your cat</h2>

<%= render 'form', action: :edit, cat: @cat %>

cats/app/views/cats/index.html.erb
<h1>All the Cats!</h1>


<% @cats.each do |cat| %>
<li><%= cat.name %></li>
<li><%= link_to "Cat info", cat_url(cat) %></li>
<% end %>

cats/app/views/cats/new.html.erb
<h2>Add your cat</h2>

<%= render 'form', action: :new, cat: @cat %>

cats/app/views/cats/show.html.erb
<h2> <%= @cat.name %> </h2>

<table>
  <tr>
    <th>Age</th>
    <th>Sex</th>
    <th>Color</th>
    <th>Description</th>
  </tr>
  <tr>
    <td> <%= @cat.age %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

  <label for="">Rental Requests</label>
  <table>
    <tr>
      <th>start date</th>
      <th>end date</th>
    </tr>
    <% @cat.rental_requests.each do |request|%>
    <tr>
      <td> <%= request.start_date %> </td>
      <td> <%= request.end_date %> </td>
      <td> <%= request.status %> </td>
      <% if request.pending? %>
        <td><form action="<%= cat_rental_request_approve_url(request) %>" method="post">
          <input type="hidden" name="_method" value="patch">
          <input type="submit" value="Approve"></form></td>
        <td><form action="<%= cat_rental_request_deny_url(request) %>" method="post">
          <input type="hidden" name="_method" value="patch">
          <input type="submit" value="Deny"></form></td>
      <% end %>
    </tr>
    <% end %>
  </table>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>